---
- fail: msg="nfspath is not defined"
  when: nfspath == ''
- fail: msg="nfsmount is not defined"
  when: nfsmount == ''

- name: install nfs packages
  apt: update_cache=yes cache_valid_time=600 name=nfs-kernel-server,nfs-common state=latest
  sudo: yes
  tags:
    - nfs

- name: stop nfs
  service: name=nfs-kernel-server state=stopped
  sudo: yes
  tags:
    - nfs

- name: unmount existing volumes
  shell: umount {{ nfspath }} || true
  sudo: yes
  tags:
    - nfs

- name: create root directory for NFS volume
  file: path={{ nfspath }} state=directory
  sudo: yes
  tags:
    - nfs

- name: create sub directory for NFS volume
  file: path={{ nfspath }} state=directory
  sudo: yes
  tags:
    - nfs

- name: create directory for NFS mount
  file: path={{ nfsmount }} state=directory
  sudo: yes
  tags:
    - nfs

- name: mount NFS volume
  shell: mount --bind {{ nfsmount }} {{ nfspath }}
  sudo: yes
  tags:
    - nfs

- name: install /etc/exports
  template: src=exports dest=/etc/exports mode=0644
  sudo: yes
  tags:
    - nfs

- name: set nfsd options
  lineinfile:
    dest: /etc/default/nfs-kernel-server
    regexp: '^RPCNFSDOPTS=.*'
    line: 'RPCNFSDOPTS="{{ nfsdopts }}"'
  sudo: yes
  tags:
    - nfs

- name: start nfs
  service: name=nfs-kernel-server state=started
  sudo: yes
  tags:
    - nfs

- name: restart idmapd
  service: name=idmapd state=restarted
  sudo: yes
  tags:
    - nfs
