---
- name: remove spurious dpkg lock file
  shell: if [ /etc/hostname -nt /var/lib/dpkg/lock ]; then rm /var/lib/dpkg/lock ; fi

- name: install vim for ops sanity
  apt: update_cache=yes cache_valid_time=600 name=vim state=latest
  sudo: yes

- name: install acct for process tracking
  apt: name=acct state=latest
  sudo: yes

- name: YOLO system upgrade
  apt: upgrade=safe
  sudo: yes

- name: install git
  apt: name=git state=latest
  sudo: yes

# May trigger a bug with aufs
- name: remove mlocate
  apt: name=mlocate state=absent
  sudo: yes

- include: ssh.yml
- include: python.yml
